config/routes.rb
Scaphon::Application.routes.draw do
  ### All for authentication ###
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  resources :users
  resources :sessions

  root to: "home#index"

  resources :supporters do
    resources :pictures
    resources :attachments
  end

  resources :abouts do
    resources :pictures
  end

  resources :board_members do
    resources :pictures
  end

  resources :communities do
    resources :pictures
    resources :attachments
  end

  resources :scholarships do
    resources :pictures
    resources :attachments
  end

  resources :affairs do
    resources :pictures
    resources :attachments
  end

  resources :newsletters do
    resources :pictures
    resources :attachments
  end

  resources :password_resets
  resources :newsletter_blasts
end

app/models/affair.rb
class Affair < ActiveRecord::Base
  has_many :pictures, as: :imageable
  has_many :attachments, as: :fileable
end

app/controllers/affairs_controller.rb
class AffairsController < ApplicationController
  before_filter :authorize, except: [:index]
  before_action :set_affair, only: [:show, :edit, :update, :destroy]

  # GET /affairs
  # GET /affairs.json
  def index
    @affairs = Affair.all.order(updated_at: :desc)
    @thisModel = Affair.all
  end

  # GET /affairs/1
  # GET /affairs/1.json
  def show
    @affair  = Affair.find(params[:id])

    @imageable   = @affair
    @pictures    = @imageable.pictures
    @picture     = Picture.new

    @fileable    = @affair
    @attachments = @fileable.attachments
    @attachment  = Attachment.new

    @thisModel =  Affair.find(params[:id])
  end

  # GET /affairs/new
  def new
    @affair = Affair.new
  end

  # GET /affairs/1/edit
  def edit
  end

  # POST /affairs
  # POST /affairs.json
  def create
    @affair = Affair.new(affair_params)

    respond_to do |format|
      if @affair.save
        format.html { redirect_to @affair, notice: 'Affair was successfully created.' }
        format.json { render action: 'show', status: :created, location: @affair }
      else
        format.html { render action: 'new' }
        format.json { render json: @affair.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /affairs/1
  # PATCH/PUT /affairs/1.json
  def update
    respond_to do |format|
      if @affair.update(affair_params)
        format.html { redirect_to @affair, notice: 'Affair was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @affair.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /affairs/1
  # DELETE /affairs/1.json
  def destroy
    @affair.destroy
    respond_to do |format|
      format.html { redirect_to affairs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_affair
      @affair = Affair.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def affair_params
      params.require(:affair).permit(:kind, :name, :date, :location, :cost, :paypal, :description)
    end
end

app/views/affairs/_form.html.erb
<div class="style-form">
  <%= form_for(@affair) do |f| %>
    <% if @affair.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@affair.errors.count, "error") %> prohibited this affair from being saved:</h2>

        <ul>
        <% @affair.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  <div class="field">
    <%= f.label :kind, class: "required" %>
    <%= f.select :kind, options_for_select([["Conference", "conference"],
                                            ["Quarterly", "quarterly"],
                                            ["Event", "event"]], @affair.kind), :required => true %>
  </div>
  <div class="field">
    <%= f.label :name, class: "required" %><br>
    <%= f.text_field :name, :required => true %>
  </div>
  <div class="field">
    <%= f.label :date, class: "required" %><br>
    <%= f.date_select :date, :required => true %>
  </div>
  <div class="field">
    <%= f.label :location, class: "required" %><br>
    <%= f.text_field :location, :required => true %>
  </div>
  <div class="field">
    <%= f.label :cost, class: "required" %><br>
    <span class="d-n-b">$</span><span class="d-n-b"><%= f.text_field :cost, :required => true %></span>
  </div>
  <div class="field">
    <%= f.label :paypal %><br>
    <%= f.text_area :paypal %>
  </div>
    <div class="field">
    <%= f.label :description, class: "required" %><br>
    <%= f.text_area :description, :required => true %>
  </div>
  <div class="actions">
    <%= f.submit class: "button" %>
  </div>
  <% end %>
</div>

app/views/affairs/edit.html.erb
<div class="row">
  <br>
  <%= link_to 'Show', @affair, class: "button" %>
  <%= link_to 'Back', affairs_path, class: "button" %>
  <br>
  <br>
    <div class="background-a small-box">
    <h1 class="center">Editing Event</h1>
    <div class="background-a-content">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/affairs/index.html.erb
<div class="row">
  <% if admin %>
    <div class="small-12 columns">
      <h2>
        <i class="fa fa-plus"></i>
        <%= link_to 'New Event', new_affair_path, class: "button" %>
      </h2>
    </div>
  <% end %>
  <div class="small-12 columns">
    <%= render "module/no_content" %>
  </div>
</div>
<% @affairs.each do |affair| %>
<div class="row">
  <div class="large-4 small-12 columns">
    <div class="image">
      <br>
      <br>
      <% if defined? affair.pictures.last.image %>
        <%= image_tag affair.pictures.last.image.url(:large) %>
      <% end %>
    </div>
  </div>
  <div class="large-8 small-12 columns background-a">
    <h1><%= affair.name %></h1>
    <div class="background-a-content">
      <h2><%= affair.date.strftime("%m/%d/%Y") %></h2>
      <h3><%= affair.location %></h3>
      <h3>$<%= affair.cost %></h3>
      <% if current_user %>
        <div id="new_pp_code">
          <div style="display:none" id="initial_paypal_code">
            <%= affair.paypal %>
          </div>
        </div>
      <% else %>
        <br>
        <h4>Please log-in <br>to purchase ticket</h4>
        <div class="log-in">
          <%= link_to "LOG IN", log_in_path, style: "color:#67c0de;text-decoration:none;font-weight:700;" %>
          <i class="fa fa-toggle-on"></i>
        </div>
      <% end %>
      <% if defined? @affair.attachments.last.file %>
        <a class="button" href="<%= @affair.attachments.last.file.url %>" >
          <i class="fa fa-file-pdf-o"></i>
          View PDF
        </a>
      <% end %>
      <% if admin %>
        <h2>
          <i class="fa fa-edit"></i>
          <%= link_to 'Edit', edit_affair_path(affair), class: "button" %>
        </h2>
        <h2>
          <i class="fa fa-plus"></i>
          <%= link_to 'Add Image/PDF/DOC', affair, class: "button" %>
        </h2>
        <h2>
          <i class="fa fa-trash"></i>
          <%= link_to 'Destroy', affair, method: :delete, data: { confirm: 'Are you sure?' }, class: "button" %>
        </h2>
      <% end %>
    </div>
  </div>
</div>
<% end %>

app/views/affairs/new.html.erb
<div class="row">
  <br>
  <%= link_to 'Back', affairs_path, class: "button" %>
  <br>
  <br>
    <div class="background-a small-box">
    <h1 class="center">New Event</h1>
    <div class="background-a-content">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/affairs/show.html.erb
<div class="row">
  <div class="small-12 columns">
    <br>
    <br>
    <br>
  </div>

  <div class="large-2 small-12 columns">
    <% if defined? @affair.pictures.last.image %>
      <br>
      <br>
      <div class="image">
        <%= image_tag @affair.pictures.last.image.url(:xlarg) %>
      </div>
    <% end %>
  </div>
  <div class="large-10 small-12 columns background-a">
    <h1><%= @affair.name %></h1>
    <div class="background-a-content">
      <h3><%= @affair.date.strftime("%m/%d/%Y") %></h3>
      <h3><%= @affair.location %></h3>
      <p><%= @affair.description %></p>
      <h2>$<%= @affair.cost %></h2>
      <div id="new_pp_code">
        <div style="display:none" id="initial_paypal_code">
          <%= @affair.paypal %>
        </div>
      </div>
      <% if defined? @affair.attachments.last.file %>
      <a class="button" href="<%= @affair.attachments.last.file.url %>" >
        <i class="fa fa-file-pdf-o"></i>
        View PDF
      </a>
      <% end %>
      <%= link_to 'Edit', edit_affair_path(@affair), class: "button" %>
      <%= link_to 'Back', affairs_path, class: "button" %>
    </div>
  </div>

  <div class="small-12 columns">
    <%= render "module/picture_attachment" %>
  </div>
</div>