config/routes.rb
Scaphon::Application.routes.draw do
  ### All for authentication ###
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  resources :users
  resources :sessions

  root to: "home#index"

  resources :supporters do
    resources :pictures
    resources :attachments
  end

  resources :abouts do
    resources :pictures
  end

  resources :board_members do
    resources :pictures
  end

  resources :communities do
    resources :pictures
    resources :attachments
  end

  resources :scholarships do
    resources :pictures
    resources :attachments
  end

  resources :affairs do
    resources :pictures
    resources :attachments
  end

  resources :newsletters do
    resources :pictures
    resources :attachments
  end

  resources :password_resets
  resources :newsletter_blasts
end

app/models/scholarship.rb
class Scholarship < ActiveRecord::Base
  has_many :pictures, as: :imageable
  has_many :attachments, as: :fileable
end

app/controllers/scholarships_controller.rb
class ScholarshipsController < ApplicationController
  before_filter :authorize, except: [:index]
  before_action :set_scholarship, only: [:show, :edit, :update, :destroy]

  # GET /scholarships
  # GET /scholarships.json
  def index
    @scholarships = Scholarship.all
    @thisModel = Scholarship.all
  end

  # GET /scholarships/1
  # GET /scholarships/1.json
  def show
    @scholarship  = Scholarship.find(params[:id])

    @imageable   = @scholarship
    @pictures    = @imageable.pictures
    @picture     = Picture.new

    @fileable    = @scholarship
    @attachments = @fileable.attachments
    @attachment  = Attachment.new

    @thisModel =  Scholarship.find(params[:id])
  end

  # GET /scholarships/new
  def new
    @scholarship = Scholarship.new
  end

  # GET /scholarships/1/edit
  def edit
  end

  # POST /scholarships
  # POST /scholarships.json
  def create
    @scholarship = Scholarship.new(scholarship_params)

    respond_to do |format|
      if @scholarship.save
        format.html { redirect_to @scholarship, notice: 'Scholarship was successfully created.' }
        format.json { render action: 'show', status: :created, location: @scholarship }
      else
        format.html { render action: 'new' }
        format.json { render json: @scholarship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scholarships/1
  # PATCH/PUT /scholarships/1.json
  def update
    respond_to do |format|
      if @scholarship.update(scholarship_params)
        format.html { redirect_to @scholarship, notice: 'Scholarship was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @scholarship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scholarships/1
  # DELETE /scholarships/1.json
  def destroy
    @scholarship.destroy
    respond_to do |format|
      format.html { redirect_to scholarships_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scholarship
      @scholarship = Scholarship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scholarship_params
      params.require(:scholarship).permit(:name, :author, :info)
    end
end

app/views/scholarships/_form.html.erb
<div class="style-form">
  <%= form_for(@scholarship) do |f| %>
    <% if @scholarship.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@scholarship.errors.count, "error") %> prohibited this scholarship from being saved:</h2>

        <ul>
        <% @scholarship.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
  <!--   <div class="field">
      <%= f.label :author %><br>
      <%= f.text_field :author %>
    </div> -->
    <div class="field">
      <%= f.label :info %><br>
      <%= f.text_area :info %>
    </div>
    <div class="actions">
      <%= f.submit class: "button" %>
    </div>
  <% end %>
</div>

app/views/scholarships/edit.html.erb
<div class="row">
  <%= link_to 'Show', @scholarship, class: "button" %>
  <%= link_to 'Back', scholarships_path, class: "button" %>
  <br>
  <br>
    <div class="background-a small-box">
    <h1 class="center">Editing Scholarship</h1>
    <div class="background-a-content">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/scholarships/index.html.erb
<div class="row">
  <% if admin %>
    <div class="small-12 columns">
      <h2>
        <i class="fa fa-plus"></i>
        <%= link_to 'New Scholarship', new_scholarship_path, class: "button" %>
      </h2>
    </div>
  <% end %>
  <div class="small-12 columns">
    <%= render "module/no_content" %>
  </div>
</div>
<div class="row">
  <% @scholarships.each do |scholarship| %>
    <div class="small-12 columns background-a">
      <h1><%= scholarship.name %></h1>
      <div class="background-a-content">
        <h4><%= scholarship.author %></h4>
        <p>
          <% if defined? scholarship.pictures.last.image %>
            <%= image_tag scholarship.pictures.last.image.url(:medium) %>
          <% end %>
          <%= scholarship.info %>
        </p>
        <div class="download-button">
          <% if defined? scholarship.attachments.last.file %>
            <a class="button" href="<%= scholarship.attachments.last.file %>" >
              <i class="fa fa-download"></i>
              download scholarship form
            </a>
          <% end %>
        </div>
          <% if admin %>
            <h2>
              <i class="fa fa-edit"></i>
              <%= link_to 'Edit', edit_scholarship_path(scholarship), class: "button"%>
            </h2>
            <h2>
              <i class="fa fa-plus"></i>
              <%= link_to 'Add Image/PDF', scholarship, class: "button" %>
            </h2>
            <h2>
              <i class="fa fa-trash"></i>
              <%= link_to 'Destroy', scholarship, method: :delete, data: { confirm: 'Are you sure?' }, class: "button"%>
            </h2>
          <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/scholarships/new.html.erb
<div class="row">
  <%= link_to 'Back', scholarships_path, class: "button" %>
  <br>
  <br>
    <div class="background-a small-box">
    <h1 class="center">New Scholarship</h1>
    <div class="background-a-content">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/scholarships/show.html.erb
<div class="row">
  <%= link_to 'Back', scholarships_path, class: "button" %>
  <br>
  <br>
</div>
<div class="row">
  <div class="small-12 columns background-a">
    <h1><%= @scholarship.name %></h1>
    <div class="background-a-content">
      <h4><%= @scholarship.author %></h4>
      <p>
        <% if defined? @scholarship.pictures.last.image %>
          <%= image_tag @scholarship.pictures.last.image.url(:medium) %>
        <% end %>
        <%= markdown(@scholarship.info) %>
      </p>
      <div class="download-button">
        <% if defined? @scholarship.attachments.last.file %>
          <a class="button" href="<%= @scholarship.attachments.last.file %>" >
            <i class="fa fa-download"></i>
            download scholarship form
          </a>
        <% end %>
      </div>
      <%= link_to 'Edit', edit_scholarship_path(@scholarship), class: "button"%>
      <%= link_to 'Destroy', @scholarship, method: :delete, data: { confirm: 'Are you sure?' }, class: "button"%>
    </div>
  </div>
</div>

<div class="row">
  <div class="small-12 columns">
    <%= render "module/picture_attachment" %>
  </div>
</div>