config/routes.rb
Scaphon::Application.routes.draw do
  ### All for authentication ###
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  resources :users
  resources :sessions

  root to: "home#index"

  resources :supporters do
    resources :pictures
    resources :attachments
  end

  resources :abouts do
    resources :pictures
  end

  resources :board_members do
    resources :pictures
  end

  resources :communities do
    resources :pictures
    resources :attachments
  end

  resources :scholarships do
    resources :pictures
    resources :attachments
  end

  resources :affairs do
    resources :pictures
    resources :attachments
  end

  resources :newsletters do
    resources :pictures
    resources :attachments
  end

  resources :password_resets
  resources :newsletter_blasts
end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
  has_many :pictures, as: :imageable
  has_many :attachments, as: :fileable
end

app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationController
  before_action :set_newsletter, only: [:show, :edit, :update, :destroy]

  # GET /newsletters
  # GET /newsletters.json
  def index
    @newsletters  = Newsletter.all.order(updated_at: :desc)
    @thisModel  = Newsletter.all
  end

  # GET /newsletters/1
  # GET /newsletters/1.json
  def show
    @imageable   = Newsletter.find(params[:id])
    @pictures    = @imageable.pictures

    @picture     = Picture.new

    @fileable    = @newsletter

    @attachments = @fileable.attachments
    @attachment  = Attachment.new

    @thisModel   = Newsletter.find(params[:id])
  end

  # GET /newsletters/new
  def new
    @newsletter = Newsletter.new
  end

  # GET /newsletters/1/edit
  def edit
  end

  # POST /newsletters
  # POST /newsletters.json
  def create
    @newsletter = Newsletter.new(newsletter_params)

    respond_to do |format|
      if @newsletter.save
        format.html { redirect_to @newsletter, notice: 'Newsletter was successfully created.' }
        format.json { render action: 'show', status: :created, location: @newsletter }
      else
        format.html { render action: 'new' }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /newsletters/1
  # PATCH/PUT /newsletters/1.json
  def update
    respond_to do |format|
      if @newsletter.update(newsletter_params)
        format.html { redirect_to @newsletter, notice: 'Newsletter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newsletters/1
  # DELETE /newsletters/1.json
  def destroy
    @newsletter.destroy
    respond_to do |format|
      format.html { redirect_to newsletters_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_newsletter
      @newsletter = Newsletter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def newsletter_params
      params.require(:newsletter).permit(:name, :date)
    end
end

app/views/newsletters/_form.html.erb
<div class="style-form">
  <%= form_for(@newsletter) do |f| %>
    <% if @newsletter.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@newsletter.errors.count, "error") %> prohibited this newsletter from being saved:</h2>

        <ul>
        <% @newsletter.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name, class: "required" %><br>
      <%= f.text_field :name, :required => true %>
    </div>
    <div class="field">
      <%= f.label :date, class: "required" %><br>
      <%= f.date_select :date, :required => true %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/newsletters/edit.html.erb
<div class="row">
  <%= link_to 'Back', newsletters_path, class: "button" %>
  <br>
  <br>
    <div class="background-a small-box">
    <h1 class="center">Editing Newsletter</h1>
    <div class="background-a-content">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/newsletters/index.html.erb
<div class="row">
  <% if admin %>
    <div class="small-12 columns">
      <h2>
        <i class="fa fa-plus"></i>
        <%= link_to 'New Newsletter', new_newsletter_path, class: "button" %>
      </h2>
    </div>
  <% end %>
  <div class="small-12 columns">
    <%= render "module/no_content" %>
  </div>
</div>
<% @newsletters.each do |newsletter| %>
  <div class="row">
    <div class="large-4 small-12 columns">
      <div class="image">
        <% if defined? newsletter.pictures.last.image %>
          <br>
          <br>
          <%= image_tag newsletter.pictures.last.image.url(:large) %>
        <% end %>
      </div>
    </div>
    <div class="large-8 small-12 columns background-a">
      <h1><%= newsletter.name %></h1>
      <div class="background-a-content">
        <h2><%= newsletter.date.strftime("%m/%d/%Y") %></h2>
        <% if defined? newsletter.attachments.last.file %>
          <div class="download-button">
            <a class="button" href="<%= newsletter.attachments.last.file.url %>" >
              <i class="fa fa-file-pdf-o"></i>
              View PDF
            </a>
          </div>
        <% end %>
        <% if admin %>
          <h2>
            <i class="fa fa-edit"></i>
            <%= link_to 'Edit', edit_newsletter_path(newsletter), class: "button" %>
          </h2>
          <h2>
            <i class="fa fa-plus"></i>
            <%= link_to 'Add Image/PDF', newsletter, class: "button" %>
          </h2>
          <h2>
            <i class="fa fa-send-o"></i>
            <%= link_to "Email Blast", new_newsletter_blast_path, data: { confirm: 'Are you sure?' }, class: "button" %>
          </h2>
          <h2>
            <i class="fa fa-trash"></i>
            <%= link_to 'Destroy', newsletter, method: :delete, data: { confirm: 'Are you sure?' }, class: "button" %>
          </h2>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/newsletters/new.html.erb
<div class="row">
  <%= link_to 'Back', newsletters_path, class: "button" %>
  <br>
  <br>
    <div class="background-a small-box">
    <h1 class="center">New Newsletter</h1>
    <div class="background-a-content">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/newsletters/show.html.erb
<div class="row">
  <div class="small-12 columns">
    <br>
    <br>
    <br>
  </div>

  <div class="large-6 small-12 columns">
    <% if defined? @newsletter.pictures.last.image %>
      <div class="image">
        <%= image_tag @newsletter.pictures.last.image.url(:xlarg) %>
      </div>
    <% end %>
  </div>
  <div class="large-6 small-12 columns background-a">
    <h1><%= @newsletter.name %></h1>
    <div class="background-a-content">
      <h3><%= @newsletter.date.strftime("%m/%d/%Y") %></h3>
      <% if defined? @newsletter.attachments.last.file %>
        <a class="button" href="<%= @newsletter.attachments.last.file %>" >
          <i class="fa fa-download"></i>
          download Scoop
        </a>
      <% end %>
      <%= link_to 'Edit', edit_newsletter_path(@newsletter), class: "button" %>
      <%= link_to 'Back', newsletters_path, class: "button" %>
    </div>
  </div>

  <div class="small-12 columns">
    <%= render "module/picture_attachment" %>
  </div>
</div>