config/routes.rb
Scaphon::Application.routes.draw do
  ### All for authentication ###
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  resources :users
  resources :sessions

  root to: "home#index"

  resources :supporters do
    resources :pictures
    resources :attachments
  end

  resources :abouts do
    resources :pictures
  end

  resources :board_members do
    resources :pictures
  end

  resources :communities do
    resources :pictures
    resources :attachments
  end

  resources :scholarships do
    resources :pictures
    resources :attachments
  end

  resources :affairs do
    resources :pictures
    resources :attachments
  end

  resources :newsletters do
    resources :pictures
    resources :attachments
  end

  resources :password_resets
  resources :newsletter_blasts
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password validations: false
  # validates :password, presence: true, length: { minimum: 2 }
  validates :email, uniqueness: true

  before_create { generate_token(:auth_token) }


  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!(validate: false)
    UserMailer.password_reset(self).deliver
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  def self.search(search)
    if search
      where('last_name LIKE ?', "%#{search}%")
    else
      scoped
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authorize, only: [:index, :show]
  helper_method :sort_column, :sort_direction
  def index
    @users = User.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 420, :page => params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      cookies[:auth_token] = @user.auth_token
      UserMailer.welcome_email(@user).deliver
      redirect_to root_url, notice: 'your logged in!'
    else
      render "new"
    end
  end

  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    def set_supporter
      @user = User.find(params[:id])
    end
    def user_params
      params.require(:user).permit(:email, :password, :first_name, :last_name,
                                   :city, :state, :zip, :phone_home, :phone_work, :nurse,
                                   :institution, :rn_id, :state_registerd, :aphon_member,
                                   :street_address, :aphon_member_number,
                                   :aphon_expiration_date, :password_reset_sent_at, :admin)
    end

    def sort_column
      User.column_names.include?(params[:sort]) ? params[:sort] : "email"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/views/users/_form.html.erb
<div class="style-form">
  <%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="row">
      <div class="small-4 columns">
        <% if admin %>
          <div class="field">
            <h2>
              <i class="fa fa-plus float-left"></i>
              Make Admin
              <%= f.check_box :admin %>
            </h2>
          </div>
        <% end %>
        <div class="field">
          <%= f.label :email, class: "required" %><br>
          <%= f.email_field :email, :required => true, :pattern => '[^@]+@[^@]+\.[a-zA-Z]{2,6}', :placeholder => "jane@smith.com" %>
        </div>
        <% if current_page? sign_up_path %>
          <div class="field">
            <%= f.label :password, class: "required" %><br>
            <%= f.password_field :password, :required => true %>
          </div>
          <div class="field">
            <%= f.label :password_confirmation, class: "required" %>
            <%= f.password_field :password_confirmation, :required => true %>
          </div>
        <% end %>
        <div class="field">
          <%= f.label :first_name, class: "required" %><br>
          <%= f.text_field :first_name, :required => true %>
        </div>
        <div class="field">
          <%= f.label :last_name, class: "required" %><br>
          <%= f.text_field :last_name, :required => true %>
        </div>
      </div>
      <div class="small-4 columns">
        <div class="field">
          <%= f.label :street_address %><br>
          <%= f.text_field :street_address %>
        </div>
        <div class="field">
          <%= f.label :city %><br>
          <%= f.text_field :city %>
        </div>
        <div class="field">
          <%= f.label :state %><br>
          <%= f.text_field :state, :class => "small" %>
        </div>
        <div class="field">
          <%= f.label :zip %><br>
          <%= f.number_field :zip, class: "small" %>
        </div>
        <div class="field">
          <%= f.label :phone_home %><br>
          <%= f.text_field :phone_home, :pattern =>'^\d{3}-\d{3}-\d{4}$', :placeholder => '333-444-5555', :class => "small" %>
        </div>
        <div class="field">
          <%= f.label :phone_work %><br>
          <%= f.text_field :phone_work, :pattern =>'^\d{3}-\d{3}-\d{4}$', :placeholder => '333-444-5555', :class => "small" %>
        </div>
      </div>
      <div class="small-4 columns">
        <div class="field">
          <%= f.label :nurse %><br>
          <%= f.check_box :nurse %>
        </div>
        <div class="field">
          <%= f.label :institution %><br>
          <%= f.text_field :institution %>
        </div>
        <div class="field">
          <%= f.label "RN ID" %><br>
          <%= f.text_field :rn_id, class: "small" %>
        </div>
        <div class="field">
          <%= f.label :aphon_member %><br>
          <%= f.check_box :aphon_member %>
        </div>
        <div class="field">
          <%= f.label :aphon_member_number %><br>
          <%= f.text_field :aphon_member_number, class: "small" %>
        </div>
          <div class="field">
          <%= f.label :aphon_expiration_date %><br>
          <%= f.date_field :aphon_expiration_date %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="actions">
        <h2 class="center"><%= f.submit class: "button", id: "edit_user_submit" %></h2>
      </div>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="row">
  <%= link_to 'Back', @user, class: "button" %>
</div>

<div class="row">
  <div class="background-a">
    <h1 class="center">Sign Up!</h1>
    <div class="background-a-content">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div id="user-table">
  <div id="user-table-header-background"> </div>
  <div id="user-table-body">
    <table>
      <thead>
        <tr>
          <th><div class="th-inner check-all"><a class="fa fa-check"></a></div></th>
          <th><div class="th-inner"><%= sortable "email" %></div></th>
          <th><div class="th-inner"><%= sortable "last_name" %></div></th>
          <th><div class="th-inner"><%= sortable "street_address", "Address" %></div></th>
          <th><div class="th-inner"><%= sortable "city" %>City</div></th>
          <th><div class="th-inner"><%= sortable "state" %></div></th>
          <th><div class="th-inner"><%= sortable "zip" %></div></th>
          <th><div class="th-inner"><%= sortable "institution" %></div></th>
          <th><div class="th-inner"><%= sortable "state_registerd", "SR" %></div></th>
          <th><div class="th-inner"><%= sortable "aphon_member", "AM?" %></div></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= check_box_tag "class[]", user.email %></td>
            <td><a href="/users/<%= user.id %>"><%= user.email %></a></td>
            <td><%= user.last_name %>, <%= user.first_name %></td>
            <td><%= user.street_address %></td>
            <td><%= user.city %></td>
            <td><%= user.state %></td>
            <td><%= user.zip %></td>
            <td><%= user.institution %></td>
            <td><%= user.state_registerd %></td>
            <td><%= user.aphon_member %></td>
            <td>
              <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<div id="user-bar">
  <div id="print">
    <input type="button" onClick="window.print()" />
    <i class="fa fa-print"></i>
  </div>
<!--   <div id="search">
    <%= form_tag users_path, :method => 'get', :id => "users_search" do %>
      <p>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "Search", :name => nil %>
        <%= hidden_field_tag :direction, params[:direction] %>
        <%= hidden_field_tag :sort, params[:sort] %>
      </p>
    <% end %>
  </div> -->
</div>
<div class="row">
  <div id="paginate">
    <%= will_paginate @users %>
  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <%= link_to 'Back', log_in_path, class: "button" %>
  <div class="background-a">
    <h1 class="center">Sign Up!</h1>
    <div class="background-a-content">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="small-12 columns">
    <br>
    <br>
    <%= link_to 'Edit', edit_user_path(@user), class: "button" %>
  </div>
  <div class="small-12 columns background-a">
    <h1><%= @user.email %></h1>
    <div class="background-a-content">
      <p>
        <strong>First name:</strong>
        <%= @user.first_name %>
      </p>
      <p>
        <strong>Admin:</strong>
        <%= @user.admin %>
      </p>
      <p>
        <strong>Last name:</strong>
        <%= @user.last_name %>
      </p>

      <p>
        <strong>Address:</strong>
        <%= @user.street_address %>
      </p>

      <p>
        <strong>City:</strong>
        <%= @user.city %>
      </p>

      <p>
        <strong>State:</strong>
        <%= @user.state %>
      </p>

      <p>
        <strong>Zip:</strong>
        <%= @user.zip %>
      </p>

      <p>
        <strong>Phone home:</strong>
        <%= @user.phone_home %>
      </p>

      <p>
        <strong>Phone work:</strong>
        <%= @user.phone_work %>
      </p>

      <p>
        <strong>Nurse:</strong>
        <%= @user.nurse %>
      </p>

      <p>
        <strong>Institution:</strong>
        <%= @user.institution %>
      </p>

      <p>
        <strong>Rn:</strong>
        <%= @user.rn_id %>
      </p>

      <p>
        <strong>State registerd:</strong>
        <%= @user.state_registerd %>
      </p>

      <p>
        <strong>Aphon member:</strong>
        <%= @user.aphon_member %>
      </p>

      <p>
        <strong>Scaphon member:</strong>
        <%= @user.scaphon_member %>
      </p>

      <p>
        <strong>Aphon member number:</strong>
        <%= @user.aphon_member_number %>
      </p>

      <p>
        <strong>Aphon expiration date:</strong>
        <% if @user.aphon_expiration_date %><%= @user.aphon_expiration_date.strftime("%m/%d/%Y") %><% end %>
      </p>
    </div>
  </div>
</div>